name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}
  dockerhub_t: ${{ secrets.DOCKER_HUB_T }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Output Run Number
      run: echo ${{ github.run_number }}

    - name: Build the Docker image
      run: docker build --build-arg BUILD_NUM=${{ github.run_number }} -t hello:latest ./myapp
      
    - name: show_images
      run: docker images
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: run_images
      run: docker run --name hello_vova hello:latest
      
    - name: show conteiners
      run: docker ps -a
      
    - name: commit image
      run: docker commit -a "hello_vova" hello_vova vova0911/hello:latest
      
      
      

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_T }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: vova0911/hello:latest


      
    - name: show conteiners
      run: docker ps -a
      
    - name: show_images
      run: docker images

    - name: push image
      run: docker push vova0911/hello:latest 

