name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  MAJOR_NUM: '1'
  MINOR_NUM: '2'

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    # Scan directoris & files
    - uses: actions/checkout@v3
   
    - name: Build the Docker image
      run: docker build --build-arg PATCH_NUM=${{ github.run_number }} --build-arg MAJOR_NUM=$MAJOR_NUM --build-arg MINOR_NUM=$MINOR_NUM -t hello:latest ./myapp
      
    - name: show_image
      run: docker images
      
    - name: run_image
      run: docker run --name hello_vova hello:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_T }}        
    
    - name: tag version
      run: docker tag hello:latest vova0911/hello:$MAJOR_NUM.$MINOR_NUM.${{ github.run_number }}
      
    - name: tag latest
      run: docker tag hello:latest vova0911/hello:latest
     
    - name: push version
      run: docker push vova0911/hello:$MAJOR_NUM.$MINOR_NUM.${{ github.run_number }}  
      
    - name: push latest
      run: docker push vova0911/hello:latest
      
