name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: ls
      run: docker build -t hello ./myapp

  show_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: show_files
      run: ls
      #run: docker build -t hello ./myapp
    

