name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t hello:latest ./myapp
      
    - name: show_images
      run: docker images
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: run_images
      run: docker run --name hello_vova hello:latest
      
    - name: show conteiners
      run: docker ps -a
      
    - name: Login to Docker Hub
      uses: actions/checkout@v4
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_P }}
     
   # - uses: actions/checkout@v1
   # - name: Login to DockerHub Registry
   #   run: echo ${{ secrets.DOCKER_HUB_P }} | docker login -u ${{ secrets.DOCKER_HUB_U }} --password-stdin
        
    
    - name: commit image
      run: docker commit -a "hello_vova" hello_vova vova0911/hello:latest
   
      
    - name: show conteiners
      run: docker ps -a

    - name: push image
      run: docker push vova0911/hello:latest  

