name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t hello ./myapp
      
    - name: show_images
      run: docker images
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: actions/checkout@v4
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_P }}

    - name: commit image
      run: docker commit hello:latest vova0911/hello:latest      

    - name: push image
      run: docker push vova0911/hello:latest   

