name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  get_secrets:
    runs-on: ubuntu-latest
  	steps:
    - name: Hello world action
      with: 
        docker_hub_user: ${{ secrets.DOCKER_HUB_U}}
        docker_hub_pass: ${{ secrets.DOCKER_HUB_p}}


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: ls
      run: docker build -t hello ./myapp

  show_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: show_files
      run: ls
      #run: docker build -t hello ./myapp
    

