name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t hello ./myapp

  show_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ls command
      run: ls

  show_env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print_p
      run: echo $dockerhub_u

    - uses: actions/checkout@v3
    - name: print_u
      run: echo $dockerhub_p
      
    - uses: actions/checkout@v3
    - name: print_image
      run: echo $IMAGE_NAME
      

