name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build --build-arg BUILD_NUM=777 -t hello:latest ./myapp
      
    - name: run_images
      run: docker run --name hello_vova hello:latest
      
    - name: commit image
      run: docker commit -a "hello_vova" hello_vova vova0911/hello:1.0.${{ github.run_number }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_U }}
        password: ${{ secrets.DOCKER_HUB_T }}

    - name: push image
      run: docker push vova0911/hello:1.0.${{ github.run_number }}

