name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t hello ./myapp

  show_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ls command
      run: ls

  show_enc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print
      run: echo $dockerhub_u
      run: echo $dockerhub_p

