name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  dockerhub_u: ${{ secrets.DOCKER_HUB_U }}
  dockerhub_p: ${{ secrets.DOCKER_HUB_P }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t hello ./myapp
      
    - name: show_images
      run: docker images
    
  login_2_dockerhub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: actions/checkout@v4
        with:
          username: ${{ secrets.DOCKER_HUB_U }}
          password: ${{ secrets.DOCKER_HUB_P }}
          
  push_2_dockerhub:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: commit image
      run: docker commit -a "Pipeline" hello:latest vova0911/hello:latest      

    steps:
    - uses: actions/checkout@v3
    - name: push image
      run: docker push vova0911/hello:latest   

